version: "3.8"

services:
  acezero:
    restart: always
    container_name: acezero
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "7771:7007"
    volumes:
      - ./images:/workspace/images
    deploy:
      resources:
        reservations:
          devices:
            - driver: 'nvidia'
              count: all
              capabilities: [gpu]
    extra_hosts:
      - "host.docker.internal:host-gateway"
